#!/usr/bin/python

import linecache
import math
import os



f1=open("abc.txt","r")
x=f1.readlines()

count=0
ex=0
ey=0
for i in range(1600,1811):

	ex=ex+float(x[i][4:20])
	ey=ey+float(x[i][24:40])
	count=count+1
	

print ex/count,ey/count
