#!/usr/bin/python

import linecache
import math
import os



f1=open("delta","r")
x=f1.readlines()

count=0
ex=0
#ey=0
for i in range(00,10000):

	ex=ex+float(x[i][33:48])
#	ey=ey+float(x[i][15:30])
	count=count+1
	

print ex/count
