#!/usr/bin/python

import linecache
import math
import os



f1=open("abc.txt","r")
x=f1.readlines()

count=0
ex=0
ez=0
for i in range(1500,2000):

	ex=ex+float(x[i][4:19])
	ez=ez+float(x[i][21:35])

	count=count+1
	

print ex/count,ez/count
